name = "augment-token-proxy"
main = "workers/token-proxy.ts"
compatibility_date = "2024-12-01"

[vars]
ALLOWED_ORIGINS = "agmt.916919.xyz"
TENANT_URL_WHITELIST = "agmt.916919.xyz"

[observability]
enabled = true

[[rules]]
type = "Text"
globs = ["**/*.html"]

